import torch
import torch.nn as nn

class VAE(nn.Module):
    def __init__(self, input_dim=784, hidden_dim=400, latent_dim=20):
        """
        Initializes the Variational Autoencoder (VAE) model.

        Args:
            input_dim (int, optional): Dimensionality of the input data. Default is 784.
            hidden_dim (int, optional): Number of units in the hidden layer. Default is 400.
            latent_dim (int, optional): Dimensionality of the latent space. Default is 20.

        Attributes:
            encoder (nn.Sequential): Encoder network mapping input to hidden representation.
            mu_layer (nn.Linear): Linear layer to compute the mean of the latent distribution.
            logvar_layer (nn.Linear): Linear layer to compute the log-variance of the latent distribution.
            decoder (nn.Sequential): Decoder network mapping latent space back to input space.
        """
        super().__init__()
        self.encoder = nn.Sequential(
            nn.Linear(input_dim, hidden_dim),
            nn.ReLU()
        )
        self.mu_layer = nn.Linear(hidden_dim, latent_dim)
        self.logvar_layer = nn.Linear(hidden_dim, latent_dim)

        self.decoder = nn.Sequential(
            nn.Linear(latent_dim, hidden_dim),
            nn.ReLU(),
            nn.Linear(hidden_dim, input_dim),
            nn.Sigmoid()
        )

    def encode(self, x):
        """
        Encodes the input data into latent space parameters.

        Args:
            x (torch.Tensor): Input tensor to be encoded.

        Returns:
            Tuple[torch.Tensor, torch.Tensor]: A tuple containing the mean (mu) and log-variance (logvar) tensors of the latent distribution.
        """
        h = self.encoder(x)
        return self.mu_layer(h), self.logvar_layer(h)

    def reparameterize(self, mu, logvar):
        """
        Applies the reparameterization trick to sample from a Gaussian distribution.

        Given the mean (`mu`) and log-variance (`logvar`) of a Gaussian distribution, this method generates a sample using the reparameterization trick, which allows gradients to flow through stochastic nodes during backpropagation.

        Args:
            mu (torch.Tensor): The mean of the latent Gaussian distribution.
            logvar (torch.Tensor): The logarithm of the variance of the latent Gaussian distribution.

        Returns:
            torch.Tensor: A sample drawn from the Gaussian distribution parameterized by `mu` and `logvar`.
        """
        std = torch.exp(0.5 * logvar)
        eps = torch.randn_like(std)
        return mu + eps * std

    def decode(self, z):
        """
        Decodes a latent vector `z` into the reconstructed output using the decoder network.

        Args:
            z (torch.Tensor): Latent vector(s) to be decoded.

        Returns:
            torch.Tensor: Reconstructed output generated by the decoder.
        """
        return self.decoder(z)

    def forward(self, x):
        """
        Performs a forward pass through the Variational Autoencoder (VAE).

        Args:
            x (Tensor): Input tensor to the VAE.

        Returns:
            Tuple[Tensor, Tensor, Tensor]: A tuple containing:
                - The reconstructed output from the decoder.
                - The mean (mu) of the latent Gaussian distribution.
                - The log-variance (logvar) of the latent Gaussian distribution.
        """
        mu, logvar = self.encode(x)
        z = self.reparameterize(mu, logvar)
        return self.decode(z), mu, logvar

def vae_loss(x_recon, x, mu, logvar):
    """
    Computes the loss function for a Variational Autoencoder (VAE).

    This loss is composed of two terms:
        1. Reconstruction loss: Measures how well the reconstructed input (x_recon) matches the original input (x) using binary cross-entropy.
        2. KL divergence: Regularizes the learned latent distribution (parameterized by mu and logvar) to be close to a standard normal distribution.

    Args:
        x_recon (torch.Tensor): The reconstructed input from the decoder.
        x (torch.Tensor): The original input.
        mu (torch.Tensor): The mean of the latent Gaussian distribution.
        logvar (torch.Tensor): The log variance of the latent Gaussian distribution.

    Returns:
        torch.Tensor: The total VAE loss (reconstruction loss + KL divergence).
    """
    recon_loss = nn.functional.binary_cross_entropy(x_recon, x, reduction='sum')
    kl_div = -0.5 * torch.sum(1 + logvar - mu.pow(2) - logvar.exp())
    return recon_loss + kl_div

def train_vae(vae, train_loader, val_loader, epochs, optimizer):
    """
    Trains a Variational Autoencoder (VAE) model using the provided training and validation data loaders.

    Args:
        vae (torch.nn.Module): The VAE model to be trained.
        train_loader (torch.utils.data.DataLoader): DataLoader for the training dataset.
        val_loader (torch.utils.data.DataLoader): DataLoader for the validation dataset.
        epochs (int): Number of training epochs.
        optimizer (torch.optim.Optimizer): Optimizer for updating model parameters.
    """
    for epoch in range(epochs):
        vae.train()
        train_loss = 0
        for batch in train_loader:
            x = batch[0]
            optimizer.zero_grad()
            x_recon, mu, logvar = vae(x)
            loss = vae_loss(x_recon, x, mu, logvar)
            loss.backward()
            optimizer.step()
            train_loss += loss.item()

        vae.eval()
        val_loss = 0
        with torch.no_grad():
            for batch in val_loader:
                x = batch[0]
                x_recon, mu, logvar = vae(x)
                loss = vae_loss(x_recon, x, mu, logvar)
                val_loss += loss.item()

        print(f"Epoch {epoch+1}: Train Loss = {train_loss:.2f}, Val Loss = {val_loss:.2f}")
